version: '2'
services:
    facturacionportal-app:
        image: facturacionportal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://facturacionportal-postgresql:5432/facturacionPortal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=facturacionportal-elasticsearch:9300
        ports:
            - 8080:8080
    facturacionportal-postgresql:
        extends:
            file: postgresql.yml
            service: facturacionportal-postgresql
    facturacionportal-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: facturacionportal-elasticsearch
